USE [master]
GO

/****** Object:  Database [eczane]    Script Date: 12.07.2021 03:16:32 ******/
CREATE DATABASE [eczane]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eczane', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\eczane.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'eczane_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\eczane_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [eczane] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eczane].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eczane] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eczane] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eczane] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eczane] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eczane] SET ARITHABORT OFF 
GO

ALTER DATABASE [eczane] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eczane] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eczane] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eczane] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eczane] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eczane] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eczane] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eczane] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eczane] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eczane] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eczane] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eczane] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eczane] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eczane] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eczane] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eczane] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eczane] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eczane] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [eczane] SET  MULTI_USER 
GO

ALTER DATABASE [eczane] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eczane] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eczane] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eczane] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [eczane] SET  READ_WRITE 
GO

